services:
  nextjs:
    container_name: web-shavira-undiksha
    build: .
    command: sh -c "npm run build && npm run start"
    env_file:
      - .env.local
    ports:
      - "3002:3002"
    restart: always
